### PR TITLE
Support for HomeMatic/homematicIP communication

### PR DESCRIPTION
**Pull request by honsma235**
Till a few weeks ago I had Debian installed on my rock-4se with an home assistant supervised install.
That worked quite ok, until it stopped booting after I updated the OS :/. After i realized I am not able to fix the problem and I will have to install from scratch, I though I might give your fork another chance. Last time I tried, about a year ago, it didn't want to boot on my board, but this time it worked right away. Loaded my backup and it was up and running.

I was happy to leave the supervised install behind, but then I noticed that the [RaspberryMatic Addon](https://github.com/jens-maus/RaspberryMatic/wiki/Installation-HomeAssistant) was not working as it didn't find my USB RF-Module (HMIP-RFUSB).
Upon investigating your fork I noticed that the necessary kernel modules 'eq3_char_loop' and 'generic_raw_uart' aren't present. Upstream they get pulled in with "BR2_PACKAGE_RPI_RF_MOD", but neither is active in your configs for the Rock* boards.

I tested it on my rock-4se board and my RF-Module works if the packages BR2_PACKAGE_EQ3_CHAR_LOOP and BR2_PACKAGE_GENERIC_RAW_UART are activated.

I don't think there is any downside. As far as I know, they only add two kernel modules necessary for some specific hardware.

### CODE REVIEW

**Comment by citruz** [comment]
Oh now I see why the `BR2_PACKAGE_RPI_RF_MOD` package is enabled in all configs upstream even for devices that are not a raspberry pi 🙃 
We could also enable that instead of adding the two packages explicitly. I'm wondering if `BR2_PACKAGE_RPI_RF_MOD` itself is installing anything at all if none of the `BR2_PACKAGE_RPI_RF_MOD_DTS_*` options are set.

**Comment by honsma235** [comment]
I tried to enable BR2_PACKAGE_RPI_RF_MOD only and my RF-Module was working.
But I didn't dig into what actually happens inside the package.

Maybe @jens-maus could comment on this. I think he would know right away.

**Comment by citruz** [comment]
I checked and the only thing it does is installing a rules file to `/lib/udev/rules.d/`. But let's stay consistent with the other configs and enable `BR2_PACKAGE_RPI_RF_MOD` instead of the two individual packages.
Do you want to update your PR so that you are credited as a contributor? I try to keep the config options alphabetically sorted so please at it after `BR2_PACKAGE_RPCBIND`.

**Comment by honsma235** [comment]
Done.

Just for reference, here is the PR where this got added upstream: home-assistant/operating-system#1266

**Pull request merged**
